[deployment]
# Project identity
project_name = "dstdns"
environment_tag = "dev"
# repo_path is auto-detected (CWD) or set via --repo-root argument
docker_network_name_template = "{{deployment.project_name}}-{{deployment.environment_tag}}-network"
log_level = "DEBUG"