services:
  local-proxy:
    image: nginx:stable-alpine
    container_name: local-proxy
    restart: unless-stopped
    networks:
      - proxy-network
    ports:
      - "${LOCAL_TLS_BIND_HTTPS:?LOCAL_TLS_BIND_HTTPS must be set}:443"
      - "${LOCAL_TLS_BIND_HTTP:?LOCAL_TLS_BIND_HTTP must be set}:80"
    volumes:
      - "${LE_CERT_BASE:?LE_CERT_BASE must be set}:/etc/letsencrypt:ro"
      - "${LOCAL_PROXY_CONFIG_PATH:?LOCAL_PROXY_CONFIG_PATH must be set}:/etc/nginx/conf.d:ro"
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1

networks:
  proxy-network:
    external: true
    name: "${LOCAL_PROXY_NETWORK:?LOCAL_PROXY_NETWORK must be set}"
